# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ptype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.Ptype'),
            preserve_default=False,
        ),
    ]
